### ISSUE TITLE
Add toggle to sort queue by queue positions

### ISSUE THREAD

**Issue by mmrose** [kraiz/icecult#17]
At the moment, elements in the queue are sorted by it's name. 
Please add a toggle or something to sort elements by it's queue position.

**Comment by kraiz** [comment]
Ordered by priority by default as i would expect this order be default. Feeling different?
Can you please test it together with the changes from #19 (all included in current master branch)?

**Comment by mmrose** [comment]
It is ordered by priority now, but I don't know if it was before.

**Comment by kraiz** [comment]
It wasn't. Closing this :)
